# Generated by Django 3.0.3 on 2020-04-30 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200302_1929'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
